---
- name: This is to add user on instances
  hosts: all
  tasks:
    - set_fact:
        username: "{{ morpheus['customOptions']['opt_username'] }}"
        password: "{{ morpheus['customOptions']['opt_password'] }}"
        #userpass_cyper: "{{ lookup('cypher','secret=secret/userpass') }}"
    - name: Add a user
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        state: present    
    - name: Add sudoers users to wheel group
      user:
        name: "{{ username }}"
        groups: wheel
        append: yes
        state: present
        createhome: yes
