---
- name: Delete the VM
  hosts: bastion
  vars_files:
    - vars/main.yml
  vars:
    morpheus_server: "hpe-cmp.helionit.io"
    bearer_token: "ab8ec0c3-faca-4ff2-9a44-13b1411c11ff"
    cluster_name: "{{ morpheus['customOptions']['cluster_name'] }}"
    openshift_working_directory_path: "{{ ansible_env.HOME }}/{{ cluster_name }}"
  tasks: 
    # - name: Node Deployment
    #   include_role:
    #     name: master_worker_node
    #     tasks_from: add_morpheus_cluster.yml
    
    - name: Reterives the cluster ID
      uri:
        url: https://{{ morpheus_server }}/api/clusters?name={{ cluster_name }}
        method: Get
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ bearer_token }}"
        return_content: true
        validate_certs: false
        status_code: 200
        timeout: 30
      register: webpage  
    - debug:
        var: webpage.content
    - set_fact:
        # cluster_id: "{{ (webpage.content | from_json).clusters[0].id }}"
        size: "{{ (webpage.content | from_json).meta.size }}"
      # when: webpage.rc == 0
    - debug:
        var: size    

    - set_fact:
        cluster_id: "{{ (webpage.content | from_json).clusters[0].id }}"       
      when: size == "1"
      
    - name: Delete the cluster ID
      uri:
        url: https://{{ morpheus_server }}/api/clusters/{{ cluster_id }}?removeInstances=off&removeResources=on&preserveVolumes=off&releaseFloatingIps=on&releaseEIPs=on&force=off
        method: DELETE
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ bearer_token }}"
        return_content: yes
        validate_certs: false
        status_code: 200
        timeout: 30
      register: webpage
      when: size == "1"


    - name: Get OpenShift node names
      command: oc get nodes -o json
      register: oc_nodes
      environment:
        KUBECONFIG: "{{ openshift_working_directory_path }}/install-dir/auth/kubeconfig"

    - name: Extract and sanitize VM names from OpenShift nodes
      set_fact:
        vm_list: >-
          {{ oc_nodes.stdout | from_json
                           | json_query('items[*].metadata.name')
                           | map('regex_replace', '\\..*$', '') 
                           | list }}

    - name: Debug sanitized VM names
      debug:
        var: vm_list

    - name: Destroy OpenShift cluster
      shell: |
        openshift-install destroy cluster --dir {{ cluster_destroy_dir }} --log-level=info
      environment:
        KUBECONFIG: "{{ openshift_working_directory_path }}/install-dir/auth/kubeconfig"
      register: destroy_output
      ignore_errors: true

    - name: Print destroy cluster output
      debug:
        var: destroy_output.stdout_lines


    - name: Power-Off the openshift VMs
      vmware_guest:
        hostname: "{{ vcenter.host }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        validate_certs: no
        folder: "{{ vcenter.folder }}"
        name: "{{ item.name }}"
        state: poweredoff
      loop: "{{  vm_list }}"
      loop_control:
        label: "Power Off {{ item.name }}"
      ignore_errors: True
    
    - name: Delete openshift VM
      vmware_guest:
        hostname: "{{ vcenter.host }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        validate_certs: no
        folder: "{{ vcenter.folder }}"
        name: "{{ item.name }}"
        state: absent
      loop: "{{  vm_list }}"
      loop_control:
        label: "Power On {{ item.name }}"
      ignore_errors: True

