---
- name: Generate the ignition 
  hosts: bastion
  vars_files:
    - vars/main.yml
  tasks: 
    # - name: Ignition Generation
    #   include_role:
    #     name: bastion_node
        
    - name: Node Deployment
      include_role:
        name: master_worker_node

