---
- name: Morpheus Enable Cloud
  hosts: localhost
  gather_facts: yes
  vars: 
    morpheus_server: "{{ morpheus['morpheus']['applianceUrl'] }}"
    BEARER: "{{ morpheus['morpheus']['apiAccessToken'] }}"
    tenantId: "{{  morpheus['accountId'] }}"
    zoneId: "1"
    datastore_id: "2"
    network_id: "3"
    resource_pools_id: "1"
  tasks:
    - set_fact:
        #BEARER_MASTER: "{{ lookup('cypher','secret=secret/morpheusapi') }}"
        BEARER_MASTER: "b32fffe1-c2ce-466c-a515-4c785140ea33"
        
    - name: Create a group
      uri:
        url: "{{ morpheus_server }}api/groups"
        method: POST
        headers:
          Authorization: "Bearer {{ BEARER }}"
          Content-Type: "application/json"
        body: |
          {
            "group": {
              "name": "Private_clouds"
            }
          }
        body_format: json
        return_content: yes
        validate_certs: no
      register: result
      
    - name: Print result
      debug:
        var: result  
        
    - name: Extract Group IDs
      set_fact:
        GroupID: "{{ result.json.group.id }}"
        
    - name: PUT to update zones
      uri:
        url: "{{ morpheus_server }}api/groups/{{ GroupID }}/update-zones"
        method: PUT
        headers:
          Authorization: "Bearer {{ BEARER }}"
          Content-Type: "application/json"
        body: |
          {
            "group": {
              "id": {{ GroupID }},
              "zones": [
                {
                  "id": {{ zoneId }}
                }
              ]
            }
          }
        body_format: json
        return_content: yes
        validate_certs: no
        timeout: 60
      register: result
      
    - name: Update Resource Pool 
      uri:
        url: "{{ morpheus_server }}/api/zones/{{ zoneId }}/resource-pools/{{ datastore_id }}"
        method: PUT
        headers:
          accept: "application/json"
          authorization: "Bearer {{ BEARER_MASTER }}"
          content-type: "application/json"
        body: |
          {
            "resourcePool": {
              "visibility": "public",
              "resourcePermissions": {
                "all": true,
                "allPlans": true
              },
              "active": true,
              "tenantPermissions": [
                {
                  "accounts": [
                    {{ zoneId }}  
                  ]
                }
              ]
            }
          }
        body_format: json
        return_content: yes
        timeout: 60
        validate_certs: no
      register: result
      
    - name: Update data store
      uri:
        url: "{{ morpheus_server }}/api/zones/{{ zoneId }}/data-stores/{{ datastore_id }}"
        method: PUT
        headers:
          accept: "application/json"
          authorization: "Bearer {{ BEARER_MASTER }}"
          content-type: "application/json"
        body: |
          {
            "datastore": {
              "visibility": "public",
              "resourcePermissions": {
                "all": true,
                "allPlans": true
              },
              "active": true,
              "tenantPermissions": [
                {
                  "accounts": [
                    {{ zoneId }}  
                  ]
                }
              ]
            }
          }
        body_format: json
        return_content: yes
        timeout: 60
        validate_certs: no
      register: result

    - name: Update network
      uri:
        url: "{{ morpheus_server }}api/networks/{{ network_id }}"
        method: PUT
        headers:
          accept: "application/json"
          authorization: "{{ BEARER_MASTER }}"
          content-type: "application/json"
        body: |
          {
            "network": {

              "tenants": [
                {
                  "id": {{ zoneId }}
                }
              ]
            }
          }
        body_format: json
        return_content: yes
        timeout: 60
        validate_certs: no
      register: result

    
