---
- name: Morpheus Teanant onboarding
  hosts: localhost
  gather_facts: yes
  vars:
    SUBTENANTNAME: "{{ morpheus['customOptions']['SubtenantName'] }}"
    SUBTENANTUSEREMAIL: "{{ morpheus['customOptions']['subtenantuseremailInput'] }}"
    SUBTENANTUSERPASSWORD: "{{ morpheus['customOptions']['SubtenantUserPassword'] }}" 
    morpheus_server: "{{ morpheus['morpheus']['applianceUrl'] }}"
    #URL: "hpe-cmp-training.helionit.io"
    URL: "172.16.10.178"
   
  tasks:
    - set_fact:
        BEARER: "{{ lookup('cypher','secret=secret/morpheusapi') }}"
        
    - name: Create Tenant Role
      uri:
        url: "{{ morpheus_server }}api/roles?includeDefaultAccess=true"
        method: POST
        headers:
          Authorization: "Bearer {{ BEARER }}"
          Content-Type: "application/json"
        body_format: json
        body:
          role:
            authority: "{{ SUBTENANTNAME }}_tenant_role"
            description: "Tenant role sets the maximum permissions for tenant {{ SUBTENANTNAME }}"
            roleType: "account"
            baseRoleId: 77
        return_content: yes               
        validate_certs: no
      register: response  
      ignore_errors: yes     


    - name: Get Tenant ROLEID 
      uri:
        url: "{{ morpheus_server }}api/roles?phrase={{ SUBTENANTNAME }}_tenant_role"
        method: GET
        headers:
          accept: "application/json"
          Authorization: "Bearer {{ BEARER }}"
        return_content: yes
        validate_certs: no
      ignore_errors: yes
      register: response
  
    - name: Extract Account IDs
      set_fact:
        TENANTROLEID: "{{ response.json.roles | map(attribute='id') | first  }}"
        

    - name: Debug role ID
      debug:
        msg: "Role ID: {{ TENANTROLEID }}"
        
        
    - name: Create Subtenant Account
      uri:
        url: "{{ morpheus_server }}api/accounts"
        method: POST
        headers:
          Authorization: "Bearer {{ BEARER }}"
          Content-Type: "application/json"
        body_format: json
        body:
          account:
            name: "{{ SUBTENANTNAME }}"
            description: "Subtenant for {{ SUBTENANTNAME }}"
            currency: "NZD"
            subdomain: "{{ SUBTENANTNAME }}subdomain"
            role:
              id: "{{ TENANTROLEID }}"
        return_content: yes
        validate_certs: no
      ignore_errors: yes
      register: response   

    - name: Get Account IDs
      uri:
        url: "{{ morpheus_server }}api/accounts?max=25&offset=0&sort=name&direction=asc&name={{ SUBTENANTNAME }}"
        method: GET
        headers:
          accept: "application/json"
          Authorization: "Bearer {{ BEARER }}"
        return_content: yes
        validate_certs: no
      register: response

    - name: Extract Account IDs
      set_fact:
        TENANTID: "{{ response.json.accounts | map(attribute='id') | first }}"
        
    - name: Debug Response
      debug:
        var: TENANTID


    - name: create-multi-tenant-user-role
      uri:
        url: "{{ morpheus_server }}api/roles"
        method: POST
        headers:
          Authorization: "Bearer {{ BEARER }}"
          Content-Type: "application/json"
        body_format: json
        body:
          role:
            authority: "{{ SUBTENANTNAME }}role"
            description: "Multi-tenant user role. Base role for subtenants"
            roleType: "user"
            baseRoleId: 83
            multitenant: true
            multitenantLocked: false
        return_content: yes
        validate_certs: no
      ignore_errors: yes
      register: response

    - name: Get USERROLEID 
      uri:
        url: "{{ morpheus_server }}api/roles?phrase={{ SUBTENANTNAME }}role"
        method: GET
        headers:
          accept: "application/json"
          Authorization: "Bearer {{ BEARER }}"
        return_content: yes
        validate_certs: no
      register: response

    - name: Extract Account IDs
      set_fact:
        USERROLEID: "{{ response.json.roles | map(attribute='id') | first }}"
        
    - name: Debug Response
      debug:
        var: USERROLEID      
        
        

