---
- name: Morpheus Enable Cloud
  hosts: localhost
  gather_facts: yes
  vars: 
    morpheus_server: "{{ morpheus['morpheus']['applianceUrl'] }}"
    BEARER: "{{ morpheus['morpheus']['apiAccessToken'] }}"
    tenantId: "{{  morpheus['accountId'] }}"
    zoneId: "1"
    datastore_id: "2"
    network_id: "3"
    resource_pools_id: "1"
    folder_id: ""
  tasks:
    - set_fact:
        #BEARER_MASTER: "{{ lookup('cypher','secret=secret/morpheusapi') }}"
        BEARER_MASTER: "b32fffe1-c2ce-466c-a515-4c785140ea33"
        

      
    - name: Update Resource Pool 
      uri:
        url: "{{ morpheus_server }}/api/zones/{{ zoneId }}/resource-pools/{{ resource_pools_id }}"
        method: PUT
        headers:
          accept: "application/json"
          authorization: "Bearer {{ BEARER_MASTER }}"
          content-type: "application/json"
        body: |
          {
            "resourcePool": {
              "visibility": "public",
              "resourcePermissions": {
                "all": true,
                "allPlans": true
              },
              "active": true,
              "tenantPermissions": [
                {
                  "accounts": [
                    {{ zoneId }}  
                  ]
                }
              ]
            }
          }
        body_format: json
        return_content: yes
        timeout: 60
        validate_certs: no
      register: result
      
    - name: Update data store
      uri:
        url: "{{ morpheus_server }}/api/zones/{{ zoneId }}/data-stores/{{ datastore_id }}"
        method: PUT
        headers:
          accept: "application/json"
          authorization: "Bearer {{ BEARER_MASTER }}"
          content-type: "application/json"
        body: |
          {
            "datastore": {
              "visibility": "public",
              "resourcePermissions": {
                "all": true,
                "allPlans": true
              },
              "active": true,
              "tenantPermissions": [
                {
                  "accounts": [
                    {{ zoneId }}  
                  ]
                }
              ]
            }
          }
        body_format: json
        return_content: yes
        timeout: 60
        validate_certs: no
      register: result

    - name: Update Folder
      uri:
        url: "{{ morpheus_server }}/api/zones/{{ zoneId }}/folders/{{ folder_id }}"
        method: PUT
        headers:
          accept: "application/json"
          authorization: "Bearer {{ BEARER_MASTER }}"
          content-type: "application/json"
        body: |
          {
            "folder": {
              "defaultFolder": false,
              "defaultImage": false,
              "visibility": "private",
              "resourcePermissions": {
                "all": true,
                "allPlans": true
              },
              "active": true,
              "tenantPermissions": [
                {
                  "accounts": [
                    {{ zoneId }}  
                  ]
                }
              ]
            }
          }
        body_format: json
        return_content: yes
        timeout: 60
        validate_certs: no
      register: result

    
