######################################################################################################
# © 2024 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
# This AWS Content is provided subject to the terms of the AWS Customer Agreement available at
# http://aws.amazon.com/agreement or other written agreement between Customer and either
# Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.
#######################################################################################################

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.17.0
    hooks:
      - id: terraform-docs-system
        args:
          - "--output-file=README.md"
          - "--lockfile=false"
          - "--recursive=false"
          # use the below settings if there are sub-modules
          # - "--recursive=true"
          # - "--recursive-path=modules"
          - "."
