formatter: markdown table
content: |-
  # AWS Load Balancer Terraform module

  Terraform module which creates AWS Load Balancer resources.

  ## Examples

  See the **/examples** directory for working examples to reference

  - [Basic](https://dev.azure.com/petronasvsts/PETRONAS_AWS_IAC_Module/_git/terraform-aws-elb?path=/modules/alb/examples&version=GBmaster)

  ## Usage

  ### Basic

  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
