---
- name: Power-On the worker VMs
  vmware_guest:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder }}"
    name: "{{ item.name }}"
    state: poweredon
  loop: "{{ worker_nodes_list }}"
  loop_control:
    label: "Power On {{ item.name }}"

